#!/bin/sh
echo -n "* Disabling sound... "
if [ "$(uname -n)" = "am" ]
then
	modprobe snd_hda_codec_hdmi
	modprobe snd_hda_codec_realtek
	modprobe snd_hda_intel
	modprobe snd_hwdep
	modprobe snd_pcm
	modprobe snd_page_alloc
	modprobe snd_timer
	modprobe snd
	modprobe soundcore
fi
echo "done."
