#!/bin/sh
echo -n "* Enabling sound... "
modprobe soundcore
modprobe snd
modprobe snd_seq_device
modprobe snd_timer
modprobe snd_seq
modprobe snd_page_alloc
modprobe snd_pcm
modprobe snd_hwdep
modprobe snd_hda_codec
modprobe snd_hda_codec_realtek
modprobe snd_hda_intel
amixer set Headphone 100 >/dev/null
amixer set Speaker 100 >/dev/null
amixer set Master 0 >/dev/null
echo "done."
